Repository MonitorControl/MonitorControl, pull requests merged in 2019-10, with the labels that each got.

#126 🇷🇺 Russian translation
  MonitorControl.xcodeproj/project.pbxproj
  MonitorControl/Support/ru.lproj/Localizable.strings
  MonitorControl/UI/ru.lproj/Main.strings
  MonitorControl/UI/ru.lproj/MainMenu.strings
  README.md
Labels: Priority: Minor, Status: In progress, Type: Translation

#131 Fixed values for audioMuteScreenBlank being persisted to audioSpeakerVolume (#130)
  MonitorControl/Support/Utils.swift
Labels: Priority: Minor, Status: Done, Type: Bug

#138 🇺🇦 Ukrainian localisation update for the new version of app #137
  MonitorControl/Support/uk.lproj/Localizable.strings
  MonitorControl/UI/uk.lproj/Main.strings
  MonitorControl/UI/uk.lproj/MainMenu.strings
  README.md
Labels: Priority: Minor, Type: Translation

#133 Fixed contrast slider not being set with brightness (#132)
  MonitorControl/Display.swift
  MonitorControl/UI/SliderHandler.swift
Labels: Priority: Minor, Status: In progress, Type: Bug
