Repository MonitorControl/MonitorControl, pull requests merged in 2020-10, with the labels that each got.

#261 Add Polish translation
  MonitorControl.xcodeproj/project.pbxproj
  MonitorControl/Support/pl.lproj/Localizable.strings
  MonitorControl/UI/pl.lproj/Main.strings
  MonitorControl/UI/pl.lproj/MainMenu.strings
  README.md
Labels: Type: Translation

#276 Show audio muted OSD image when audio volume value is 0
  MonitorControl/Model/Display.swift
Labels: Priority: Minor, Type: Enhancement

#308 Fix French grammatical error
  MonitorControl/UI/fr.lproj/Main.strings
Labels: Priority: Minor, Type: Translation
