Repository MonitorControl/MonitorControl, pull requests merged in 2021-10, with the labels that each got.

#636 Update German Translation
  MonitorControl/UI/de.lproj/Localizable.strings
  MonitorControl/UI/de.lproj/Main.strings
Labels: Type: Translation

#633 Update Chinese (Traditional, Taiwan) translation
  MonitorControl/UI/zh-Hant-TW.lproj/Localizable.strings
  MonitorControl/UI/zh-Hant-TW.lproj/Main.strings
Labels: Status: In progress, Type: Translation

#645 feat: close preference pane using cmd + w
  MonitorControl/Extensions/Preferences+Extension.swift
  MonitorControl/Info.plist
  MonitorControlHelper/Info.plist
Labels: Type: Enhancement

#651 Update French translations
  MonitorControl/UI/fr.lproj/Localizable.strings
  MonitorControl/UI/fr.lproj/Main.strings
Labels: Type: Translation

#649 Fix library validation causing crash when debugging due to Sparkle
  MonitorControl.xcodeproj/project.pbxproj
  MonitorControl/Info.plist
  MonitorControl/MonitorControlDebug.entitlements
  MonitorControl/UI/Base.lproj/Main.storyboard
  MonitorControl/UI/de.lproj/Main.strings
  MonitorControl/UI/en.lproj/Main.strings
  MonitorControl/UI/es-419.lproj/Main.strings
  MonitorControl/UI/fr.lproj/Main.strings
  MonitorControl/UI/hu.lproj/Main.strings
  MonitorControl/UI/it.lproj/Main.strings
  MonitorControl/UI/ja.lproj/Main.strings
  MonitorControl/UI/ko.lproj/Main.strings
  MonitorControl/UI/nl.lproj/Main.strings
  MonitorControl/UI/pl.lproj/Main.strings
  MonitorControl/UI/ru.lproj/Main.strings
  MonitorControl/UI/tr.lproj/Main.strings
  MonitorControl/UI/uk.lproj/Main.strings
  MonitorControl/UI/zh-Hans.lproj/Main.strings
  MonitorControlHelper/Info.plist
Labels: Type: Bug

#654 Add Internet Access Policy
  MonitorControl.xcodeproj/project.pbxproj
  MonitorControl/InternetAccessPolicy.plist
  MonitorControl/UI/de.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/en.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/es-419.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/fr.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/hu.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/it.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/ja.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/ko.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/nl.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/pl.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/ru.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/tr.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/uk.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/zh-Hans.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/zh-Hant-TW.lproj/InternetAccessPolicy.strings
Labels: Type: Enhancement

#669 Change icon order
  MonitorControl/Info.plist
  MonitorControl/Support/MenuHandler.swift
  MonitorControlHelper/Info.plist
Labels: Type: Enhancement
