Repository MonitorControl/MonitorControl, pull requests merged in 2021-08, with the labels that each got.

#499 Add stalebot config
  .github/stale.yml
Labels: Enhancement

#295 Add GitHub Actions Build
  .github/workflows/ci.yaml
  .github/workflows/main.yml
  MonitorControl.xcodeproj/project.pbxproj
Labels: Enhancement, Priority: Minor

#516 Update issue templates with .yml format
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/discussion.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/monitor-issue.md
  .github/ISSUE_TEMPLATE/monitor-issue.yml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yml
Labels: Enhancement

#521 Update OpenCollective link
  .github/FUNDING.yml
Labels: Information

#522 Set archs to standard for releases
  MonitorControl.xcodeproj/project.pbxproj
Labels: Bug

#523 Add direct link to monitor troubleshooting wiki for monitor issues
  .github/ISSUE_TEMPLATE/monitor-issue.yml
Labels: Documentation

#534 Update issue templates after label changes
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/discussion.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/monitor-issue.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: Documentation

#532 Add some zh-Hans translations
  MonitorControl/UI/zh-Hans.lproj/Main.strings
Labels: Translation
