Repository MonitorControl/MonitorControl, pull requests merged in 2022-05, with the labels that each got.

#1027 Added Polish translation (thanks to @Zbynius)
  MonitorControl.xcodeproj/project.pbxproj
  MonitorControl/Info.plist
  MonitorControl/UI/pl.lproj/InternetAccessPolicy.strings
  MonitorControl/UI/pl.lproj/Localizable.strings
  MonitorControl/UI/pl.lproj/Main.strings
  MonitorControlHelper/Info.plist
Labels: Type: Translation

#1025 Optimize Taiwan TC Localization
  MonitorControl/UI/zh-Hant-TW.lproj/Main.strings
Labels: Type: Translation

#1012 Use absolute paths for system framework references
  MonitorControl.xcodeproj/project.pbxproj
Labels: Type: Enhancement

#1030 Remove opening menu after onboarding
  MonitorControl/View Controllers/Onboarding/OnboardingViewController.swift
Labels: Type: Bug, Priority: Trivial

#1029 Try fixing CI + Add dependabot
  .github/.dependabot.yml
  .github/workflows/main.yml
  .gitignore
  .swiftlint.yml
  MonitorControl.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Type: Bug, Priority: Minor, Status: In progress

#1034 Updated Chinese translation
  MonitorControl/UI/zh-Hans.lproj/Main.strings
Labels: Type: Translation

#1037 Fix build scripts for m1 mac
  MonitorControl.xcodeproj/project.pbxproj
  MonitorControl/Support/Arm64DDC.swift
  MonitorControl/Support/DisplayManager.swift
  MonitorControl/Support/IntelDDC.swift
  MonitorControl/Support/KeyboardShortcutsManager.swift
  MonitorControl/Support/MediaKeyTapManager.swift
  MonitorControl/Support/SliderHandler.swift
  MonitorControl/View Controllers/Preferences/DisplaysPrefsCellView.swift
  MonitorControl/main.swift
Labels: Priority: Trivial, Status: Done, Type: Other, Architecture: arm64
