Repository MonitorControl/MonitorControl, pull requests merged in 2022-01, with the labels that each got.

#905 Adding missing Hungarian translations and fixing some typos
  MonitorControl/UI/hu.lproj/Localizable.strings
  MonitorControl/UI/hu.lproj/Main.strings
Labels: Type: Translation

#904 Add check for M1 Pro/Max Macbook Pro HDMI
  MonitorControl/Support/Arm64DDC.swift
Labels: Type: Enhancement, Priority: Minor

#880 Update menu bar icon and its behavior.
  MonitorControl/Assets.xcassets/status.imageset/Contents.json
  MonitorControl/Assets.xcassets/status.imageset/status.pdf
  MonitorControl/Assets.xcassets/status.imageset/status.png
  MonitorControl/Assets.xcassets/status.imageset/status@2x.pdf
  MonitorControl/Assets.xcassets/status.imageset/status@2x.png
  MonitorControl/Support/AppDelegate.swift
Labels: Type: Enhancement, Priority: Minor

#906 Onboarding Screen
  MonitorControl.xcodeproj/project.pbxproj
  MonitorControl/Assets.xcassets/onboarding_icon_keyboard.imageset/Contents.json
  MonitorControl/Assets.xcassets/onboarding_icon_keyboard.imageset/icon_keyboard.png
  MonitorControl/Assets.xcassets/onboarding_icon_keyboard.imageset/icon_keyboard@2x.png
  MonitorControl/Assets.xcassets/onboarding_icon_person.imageset/Contents.json
  MonitorControl/Assets.xcassets/onboarding_icon_person.imageset/icon_person.png
  MonitorControl/Assets.xcassets/onboarding_icon_person.imageset/icon_person@2x.png
  MonitorControl/Assets.xcassets/onboarding_keyboard.imageset/Contents.json
  MonitorControl/Assets.xcassets/onboarding_keyboard.imageset/onboarding_keyboard.png
  MonitorControl/Assets.xcassets/onboarding_keyboard.imageset/onboarding_keyboard@2x.png
  MonitorControl/Assets.xcassets/onboarding_keyboard.imageset/onboarding_keyboard_dark.png
  MonitorControl/Assets.xcassets/onboarding_keyboard.imageset/onboarding_keyboard_dark@2x.png
  MonitorControl/Info.plist
  MonitorControl/Support/AppDelegate.swift
  MonitorControl/Support/MediaKeyTapManager.swift
  MonitorControl/UI/Base.lproj/Main.storyboard
  MonitorControl/UI/de.lproj/Main.strings
  MonitorControl/UI/en.lproj/Main.strings
  MonitorControl/UI/es.lproj/Main.strings
  MonitorControl/UI/fr.lproj/Main.strings
  MonitorControl/UI/hu.lproj/Main.strings
  MonitorControl/UI/it.lproj/Main.strings
  MonitorControl/UI/ko.lproj/Main.strings
  MonitorControl/UI/nl.lproj/Main.strings
  MonitorControl/UI/pt-BR.lproj/Main.strings
  MonitorControl/UI/tr.lproj/Main.strings
  MonitorControl/UI/zh-Hans.lproj/Main.strings
  MonitorControl/UI/zh-Hant-TW.lproj/Main.strings
  MonitorControl/View Controllers/Onboarding/OnboardingViewController.swift
  MonitorControl/View Controllers/Preferences/AboutPrefsViewController.swift
  MonitorControl/View Controllers/Preferences/DisplaysPrefsCellView.swift
  MonitorControl/View Controllers/Preferences/DisplaysPrefsViewController.swift
  MonitorControl/View Controllers/Preferences/KeyboardPrefsViewController.swift
  MonitorControl/View Controllers/Preferences/MainPrefsViewController.swift
  MonitorControl/View Controllers/Preferences/MenuslidersPrefsViewController.swift
  MonitorControl/main.swift
  MonitorControlHelper/Info.plist
Labels: Type: Enhancement, Priority: Minor, Status: Done
